<?php

namespace Veta\HomeworkBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @return mixed
     */
    public function findMostRecent()
    {
        $qb = $this->createQueryBuilder('u')
            ->orderBy('u.dateCreate', 'DESC')

        ;
        $query = $qb->getQuery();

        return $query->execute();
    }
}
